---
- hosts: hdmhosts
  connection: local
  name: Set one-time BIOS boot device
  gather_facts: False

  vars:
    - boot_target: Pxe

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Set one-time boot device to {{ boot_target }}
      hdm_redfish_command:
        category: Systems
        command: SetOneTimeBoot
        boot_target: "{{ boot_target }}"
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: bios_onetimeboot

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
