---
- hosts: hdmhosts
  connection: local
  name: Set boot options
  gather_facts: False

  vars:
    - boot_target: Hdd
    - boot_enable: Continuous
    - boot_mode: UEFI

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Set boot options
      hdm_redfish_command:
        category: Systems
        command: SetBootDevice
        boot_target: "{{ boot_target }}"
        boot_enable: "{{ boot_enable }}"
        boot_mode: "{{ boot_mode }}"
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: bios_onetimeboot

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
