---
- hosts: hdmhosts
  connection: local
  name: Create logical drive
  gather_facts: False

  vars:
    - storage_id: RAIDStorage0
    - raid: {
        "Name": "test",
        "InitState": "No",
        "StripSize": "64KB",
        "Level": "RAID 0",
        "SpanNum": 1,
        "NumDrives": 1,
        "ReadPolicy": "Read Ahead",
        "WritePolicy": "Write Through",
        "IOPolicy": "Direct",
        "DriveCache": "Disable",
        "AccessPolicy": "Read/Write",
        "Size": 0,
        "SizeUnit": "GB",
        "PhysicalDiskList":[
            {
                "group_id": 0,
                "id": "DiskFront4"         # physical disk id
            }
        ]
    }

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 30
      register: result

    - name: Create Logical Drive
      hdm_redfish_command:
        category: Systems
        command: CreateLogicalDrive
        baseuri: "{{ baseuri }}"
        #username: "{{ username }}"
        #password: "{{ password }}"
        storage_id: "{{ storage_id }}"
        raid_details: "{{ raid }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
