---
- hosts: hdmhosts
  connection: local
  name: Delete logical drive
  gather_facts: False

  vars:
    - storage_id: RAIDStorage0
    - logical_id: LogicalDrive0

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 30
      register: result

    - name: Delete Logical Drive
      hdm_redfish_command:
        category: Systems
        command: DeleteLogicalDrive
        baseuri: "{{ baseuri }}"
        #username: "{{ username }}"
        #password: "{{ password }}"
        storage_id: "{{ storage_id }}"
        logical_id: "{{ logical_id }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
