---
- hosts: hdmhosts
  connection: local
  name: Modify logical drive
  gather_facts: False

  vars:
    - storage_id: RAIDStorage0
    - logical_id: LogicalDrive0
    - write_policy: "Write Through"
    - read_policy: "Read Ahead"
    - default_write_policy: "Write Through"
    - default_read_policy: "Read Ahead"
    - access_policy: "Read Only"
    - drive_cache: "Enable"


  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
        timeout: 30
      register: result
    
    - name: Modify Logical Drive
      hdm_redfish_command:
        category: Systems
        command: ModifyLogicalDrive
        baseuri: "{{ baseuri }}"
        #username: "{{ username }}"
        #password: "{{ password }}"
        storage_id: "{{ storage_id }}"
        logical_id: "{{ logical_id }}"
        write_policy: "{{ write_policy }}"
        read_policy: "{{ read_policy }}"
        default_read_policy: "{{ default_read_policy }}"
        default_write_policy: "{{ default_write_policy }}"
        access_policy: "{{access_policy}}"
        drive_cache: "{{drive_cache}}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
