---
- hosts: hdmhosts
  connection: local
  name: Add User
  gather_facts: False

  vars:
    - new_user: test33
    - new_pass: Password@_
    - role_id: Administrator
    - snmp_v3_enable:
    - snmp_v3_access_permission:
    - snmp_v3_auth_protocol:
    - snmp_v3_priv_protocol:
    - snmp_v3_password:

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Add user
      hdm_redfish_command:
        category: Accounts
        command: AddUser_G6_G7
        baseuri: "{{ baseuri }}"
       #  username: "{{ username }}"
       #  password: "{{ password }}"
        new_username: "{{ new_user }}"
        new_password: "{{ new_pass }}"
        roleid: "{{ role_id }}"
        snmp_v3_enable: "{{ snmp_v3_enable }}"
        snmp_v3_access_permission: "{{ snmp_v3_access_permission }}"
        snmp_v3_auth_protocol: "{{ snmp_v3_auth_protocol }}"
        snmp_v3_priv_protocol: "{{ snmp_v3_priv_protocol }}"
        snmp_v3_password: "{{ snmp_v3_password }}"
        auth_token: "{{ result.session.token }}"
        timeout: 60
        
    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
