---
- hosts: hdmhosts
  connection: local
  name: Update user role
  gather_facts: False

  vars:
    - loginname: test3
    - roleid: Operator 

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Update user role
      hdm_redfish_command:
        category: Accounts
        command: UpdateUserRole
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        account_username: "{{ loginname }}"
        roleid: "{{ roleid }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
