---
# tasks file for updaterole
- name: Update user role
  hdm_redfish_command:
    category: Accounts
    command: UpdateUserRole
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    account_username: "{{ account_username }}"
    #account_id: "{{ account_id }}"
    roleid: "{{ roleid }}"
