---
- hosts: hdmhosts
  connection: local
  name: Raid Storage Inventory
  gather_facts: False

  vars:
    datatype: RaidStorageInventory

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Define output file
      include_tasks: create_output_file.yml

    - name: Get Raid Storage Inventory
      hdm_redfish_info:
        category: Systems
        command: GetRaidStorageInventory
        baseuri: "{{ baseuri }}"
        # username: "{{ username }}"
        # password: "{{ password }}"
        auth_token: "{{ result.session.token }}"
      register: result_psu

    - name: Copy results to output file
      copy:
        content: "{{ result_psu | to_nice_json }}"
        dest: "{{ template }}.json"

    - name: Delete session using security token created by CreateSesssion above
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
