---
- hosts: hdmhosts
  connection: local
  name: Set NTP Servers
  gather_facts: False

  vars:
    - attribute_name: TertiaryNtpServer
    - attribute_value: 192.168.1.2

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Set {{ attribute_name }} to {{ attribute_value }}
      hdm_redfish_command:
        category: Manager
        command: SetNTPServers
        baseuri: "{{ baseuri }}"
        attribute_name: "{{ attribute_name }}"
        attribute_value: "{{ attribute_value }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
