---
# tasks file for getBiosattr
- name: Get BIOS attributes
  hdm_redfish_info:
    category: Systems
    command: GetBiosAttributes
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr
