---
# tasks file for setbootdevice
- name: Set boot options
  hdm_redfish_command:
    category: Systems
    command: SetBootDevice
    boot_target: "{{ boot_target }}"
    boot_enable: "{{ boot_enable }}"
    boot_mode: "{{ boot_mode }}"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: bios_attribute
