---
- hosts: hdmhosts
  connection: local
  name: Manage System Power - Greaceful restart
  gather_facts: False

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Restart system power gracefully
      hdm_redfish_command:
        category: Systems
        command: PowerReboot
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"

    - name: Delete session
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
