---
# tasks file for settimezone
- name: Set TimeZone to {{ attribute_value }}
  hdm_redfish_command:
    category: Manager
    command: SetTimeZone
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
    attribute_name: TimeZone
    attribute_value: "{{ attribute_value }}"
