---
- hosts: hdmhosts
  connection: local
  name: Delete User
  gather_facts: False

  vars:
    - account_id: 4

  tasks:
    - name: Create session
      hdm_redfish_command:
        category: Sessions
        command: CreateSession
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result

    - name: Delete user
      hdm_redfish_command:
        category: Accounts
        command: DeleteUser
        baseuri: "{{ baseuri }}"
        account_id: "{{ account_id }}"
        auth_token: "{{ result.session.token }}"
        timeout: 60


    - name: Delete session
      hdm_redfish_command:
        category: Sessions
        command: DeleteSession
        baseuri: "{{ baseuri }}"
        auth_token: "{{ result.session.token }}"
        session_uri: "{{ result.session.uri }}"
