---
# tasks file for setonetimeboot
- name: Set one-time boot device to {{ boot_target }}
  hdm_redfish_command:
    category: Systems
    command: SetOneTimeBoot
    boot_target: "{{ boot_target }}"
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: bios_attribute
