---
# tasks file for powerforceoff
- name: Turn system power off
  hdm_redfish_command:
    category: Systems
    command: PowerForceOff
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
