---
# tasks file for get logical drive details
- name: Get Logical Drive Inventory
  hdm_redfish_info:
    category: Systems
    command: GetLogicalDriveInventory
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result_attr
